export const LENS_KEYWORDS = {
  workforce_ai: {
    high_confidence: [
      'AI in HR', 'HRIS AI', 'AI recruiting', 'AI hiring', 'AI talent acquisition',
      'AI performance management', 'people analytics', 'workforce analytics',
      'predictive analytics HR', 'AI onboarding', 'AI screening', 'resume parsing',
      'AI interview', 'chatbot HR', 'conversational AI HR', 'AI payroll',
      'AI benefits', 'AI compliance', 'HR technology', 'HR tech', 'HRtech',
      'AI-powered HR', 'machine learning HR', 'NLP HR', 'sentiment analysis employee',
      'AI engagement', 'workforce intelligence', 'talent intelligence',
      'AI workforce planning', 'algorithmic hiring', 'AI bias hiring',
      'responsible AI HR', 'AI ethics hiring', 'generative AI HR',
    ],
    medium_confidence: [
      'HRIS', 'human capital management', 'HCM', 'applicant tracking',
      'ATS', 'learning management', 'LMS', 'talent management platform',
      'employee self-service', 'HR automation', 'digital HR', 'HR digital transformation',
      'Workday', 'SAP SuccessFactors', 'Oracle HCM', 'ServiceNow HR',
    ],
  },
  productivity: {
    high_confidence: [
      'async work', 'asynchronous collaboration', 'meeting culture', 'meeting overload',
      'deep work', 'focus time', 'maker schedule', 'AI-augmented workflow',
      'AI productivity', 'AI copilot work', 'AI assistant enterprise',
      'workflow automation', 'process efficiency', 'operational efficiency',
      'time management workforce', 'employee productivity', 'team productivity',
      'knowledge management', 'documentation culture', 'collaboration tools',
      'hybrid productivity', 'remote productivity', 'distributed team efficiency',
      'four-day work week', '4-day work week', 'flexible work', 'work design',
      'meeting-free', 'no-meeting', 'digital workplace', 'employee experience platform',
    ],
    medium_confidence: [
      'productivity', 'efficiency', 'throughput', 'output per employee',
      'collaboration', 'teamwork tools', 'project management', 'task management',
      'Slack', 'Teams', 'Notion', 'Asana', 'Monday.com', 'workplace technology',
      'burnout', 'cognitive overload', 'context switching',
    ],
  },
  people_strategy: {
    high_confidence: [
      'org design', 'organizational design', 'organization design',
      'skills taxonomy', 'skills-based', 'skills-first', 'skills economy',
      'internal mobility', 'talent marketplace', 'internal talent marketplace',
      'succession planning', 'workforce planning', 'strategic workforce planning',
      'talent pipeline', 'skills gap', 'reskilling', 'upskilling', 'reskill', 'upskill',
      'DEI analytics', 'pay equity', 'compensation analytics', 'total rewards',
      'employee value proposition', 'EVP', 'employer brand', 'employer branding',
      'talent acquisition strategy', 'hiring strategy', 'recruitment strategy',
      'people operations', 'people strategy', 'CHRO', 'chief people officer',
      'chief human resources', 'head of people', 'VP people',
      'employee retention', 'attrition', 'turnover', 'regrettable attrition',
      'employee lifecycle', 'talent review', 'calibration', '9-box',
    ],
    medium_confidence: [
      'hiring', 'recruiting', 'onboarding', 'offboarding', 'talent',
      'headcount', 'FTE', 'workforce', 'human resources', 'HR strategy',
      'compensation', 'benefits', 'performance review', 'performance cycle',
      'OKR', 'KPI', 'employee survey', 'engagement survey', 'eNPS',
      'job architecture', 'career framework', 'career ladder', 'leveling',
    ],
  },
  leadership: {
    high_confidence: [
      'manager effectiveness', 'manager development', 'manager enablement',
      'coaching culture', 'manager as coach', 'leadership development',
      'psychological safety', 'high-performing team', 'team performance',
      'culture measurement', 'culture analytics', 'organizational culture',
      'employee engagement', 'engagement driver', 'engagement score',
      'leadership pipeline', 'leadership capability', 'executive development',
      'feedback culture', 'continuous feedback', '360 feedback',
      'one-on-one', '1:1 meeting', 'skip-level', 'manager training',
      'servant leadership', 'inclusive leadership', 'empathetic leadership',
      'change management', 'organizational change', 'transformation leadership',
      'trust at work', 'belonging', 'inclusion', 'diversity leadership',
    ],
    medium_confidence: [
      'leadership', 'management', 'team building', 'team dynamics',
      'culture', 'values', 'mission', 'employee morale', 'recognition',
      'reward', 'motivation', 'intrinsic motivation', 'autonomy',
      'empowerment', 'delegation', 'mentoring', 'sponsorship',
      'executive coaching', 'team coaching', 'facilitation',
    ],
  },
};
